trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: TerraformJob
  displayName: 'Terraform Deployment'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      packageType: 'sdk'
      version: '3.1.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      # Inicia y valida la configuración de Terraform
      terraform init
      terraform validate
    displayName: 'Terraform Init and Validate'

  - script: 'terraform plan -out=tfplan'
    displayName: 'Terraform Plan'

  - script: 'terraform apply -auto-approve tfplan'
    displayName: 'Terraform Apply'

